version: 2
registries:
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{ secrets.GH_DEPENDABOT_TOKEN }}
    replaces-base: true
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    allow:
      - dependency-type: direct
    registries:
      - npm-github
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
