version: 2
registries:
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{ secrets.GH_DEPENDABOT_TOKEN }}
    replaces-base: true
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    allow:
      - dependency-type: direct
    registries:
      - npm-github
    ignore:
      - dependency-name: "eslint"
        versions: [">=9.0.0"]
      - dependency-name: "next"
        versions: [">=15.0.0"]
      - dependency-name: "react"
        versions: [">=19.0.0"]
      - dependency-name: "tailwindcss"
        versions: [">=4.0.0"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
