#import "./fragments/marketplace-app.graphql"

query MarketplaceCollections {
  allMarketplaceCollections(
    first: 100
  ) {
    id
    title
    slug
    featured
    theme
    apps {
      ...marketplaceAppAttributes
    }
  }
}
