#import "./fragments/marketplace-app.graphql"

query MarketplaceApps(
  $categoryId: [ItemId],
  $first: IntType = 100
  $excludedAppId: ItemId
) {
  allMarketplaceApps(
    first: $first
    orderBy: _createdAt_DESC
    filter: {
      categories: { eq: $categoryId },
      id: { neq: $excludedAppId }
    }
  ) {
    ...marketplaceAppAttributes
  }
}
