#import "./fragments/image.graphql"

query MarketplaceApp($slug: String!) {
  marketplaceApp(filter: { slug: { eq: $slug } }) {
    id
    title
    description
    logo {
      ...imageAttributes
    }
    content {
      id
      title
      body
      image {
        ...imageAttributes
      }
    }
    links {
      id
      text
      url
    }
    categories {
      id
      title
      slug
    }
    builtByAurora
    pricing
  }
}
