#import "./fragments/marketplace-app.graphql"

query MarketplaceCollections {
  allMarketplaceCollections(
    first: 100
  ) {
    id
    title
    icon
    slug
    homepageDisplay
    builtByAurora
    apps {
      ...marketplaceAppAttributes
    }
  }
}
