#import "./fragments/image.graphql"

query MarketplaceApps($categoryId: [ItemId]) {
  allMarketplaceApps(
    first: 100
    orderBy: _createdAt_DESC
    filter: { categories: { eq: $categoryId } }
  ) {
    id
    title
    slug
    description
    logo {
      ...imageAttributes
    }
    categories {
      id
      title
      slug
    }
  }
}
