#import "./fragments/image.graphql"

query MarketplaceApps(
  $categoryId: [ItemId],
  $popular: BooleanType,
  $new: BooleanType,
  $builtByAurora: BooleanType
  $essential: BooleanType
  $first: IntType = 100
  $excludedAppId: ItemId
) {
  allMarketplaceApps(
    first: $first
    orderBy: _createdAt_DESC
    filter: {
      categories: { eq: $categoryId },
      popular: { eq: $popular },
      new: { eq: $new },
      builtByAurora: { eq: $builtByAurora },
      essential: { eq: $essential },
      id: { neq: $excludedAppId }
    }
  ) {
    id
    title
    slug
    description
    logo {
      ...imageAttributes
    }
    categories {
      id
      title
      slug
    }
    builtByAurora
  }
}
