fragment marketplaceAppAttributes on MarketplaceAppRecord {
  id
  title
  slug
  description
  logo {
    ...imageAttributes
  }
  categories {
    id
    title
    slug
  }
  heroImage {
    ...imageAttributes
  }
  _allReferencingMarketplaceCollections {
    id
    title
    slug
    builtByAurora
  }
}
