export enum Modals {
  Error = "error",
  DeleteListItem = "deleteListItem",
  ViewListItemDetails = "viewListItemDetails",
  AddList = "addList",
  EditList = "editList",
  DeleteList = "deleteList",
  ImportListItems = "importListItems",
  AddApiKey = "addApiKey",
  EditApiKey = "editApiKey",
  DeleteApiKey = "deleteApiKey",
  Contact = "contact",
  Invite = "invite",
  InviteConfirmed = "inviteConfirmed",
  DealDuration = "dealDuration",
  AddPlan = "addPlan",
  EditContract = "editContract",
  EditGasPrice = "editGasPrice",
  AddRuleAddress = "addRuleAddress",
  AddRuleContract = "addRuleContract",
  EditGasCollectionAddress = "editGasCollectionAddress",
  EditPlanLimitsModal = "editPlanLimitsModal",
  EditSiloAddressPermissions = "editSiloAddressPermissions",
  BridgedTokens = "bridgedTokens",
  MetaMaskNotInstalled = "metaMaskNotInstalled",
  TopUpOptions = "topUpOptions",
}
