export enum Modals {
  Error = "error",
  DeleteListItem = "deleteListItem",
  ViewListItemDetails = "viewListItemDetails",
  AddList = "addList",
  EditList = "editList",
  DeleteList = "deleteList",
  ImportListItems = "importListItems",
  AddApiKey = "addApiKey",
  EditApiKey = "editApiKey",
  DeleteApiKey = "deleteApiKey",
  Contact = "contact",
  Invite = "invite",
  InviteConfirmed = "inviteConfirmed",
  DealDuration = "dealDuration",
  MetaMaskNotInstalled = "metaMaskNotInstalled",
  BridgeToNetwork = "bridgeToNetwork",
  BridgeFromNetwork = "bridgeFromNetwork",
}
