export { default as AuroraTriangle } from "./AuroraTriangle.svg"
export { default as Borealis } from "./Borealis.svg"
export { default as Silos } from "./Silos.svg"
export { default as MetaMask } from "./MetaMask.svg"
export { default as OracleIcon } from "./Oracle.svg"
