name: CI

on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/test.yml

  dependabot:
    uses: ./.github/workflows/dependabot-auto-merge.yml
    secrets:
      GH_TOKEN: "${{ secrets.GH_DEPENDABOT_TOKEN }}"
