name: Test

on: workflow_call

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
      - name: Install
        run: yarn install --frozen-lockfile --non-interactive --prefer-offline
      - name: Check types
        run: yarn run typecheck
      - name: Lint
        run: yarn run lint --max-warnings 0
      - name: Find dead code
        run: yarn run knip
      - name: Test
        run: yarn run test
