name: Test

on: workflow_call

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: NuuzigkJCtbpf6RU
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    env:
      DATABASE_URL: postgresql://postgres:NuuzigkJCtbpf6RU@localhost:5432/app

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
      - name: Setup NPM token
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc
      - name: Install
        run: yarn install --frozen-lockfile --non-interactive --prefer-offline
      - name: Check types
        run: yarn run typecheck
      - name: Lint
        run: yarn run lint --max-warnings 0
      - name: Find dead code
        run: yarn run knip
      - name: Test
        run: yarn run test
      - name: Test database migration
        run: npx prisma migrate deploy
